// QUESTÃO 1  comparadores
console.log("QUESTÃO 1")
/*Criar variaveis que guardem dois numeros.*/
const numero1 = 21  
const numero2 = 8

/*Imprimir na tela as seguintes mensagens:*/
/* 1-> O primeiro numero é identico ao segundo? True/False*/
const condicao1 = numero1 === numero2 
console.log(`1-> O ${numero1} é identico ao ${numero2}? ${condicao1}`)
    

/* 2-> O primeiro numero é diferente do segundo?True/False*/
const condicao2 = numero1 !== numero2 
console.log(`2-> O ${numero1} é diferente de ${numero2}? ${condicao2}`)
    

/* 3-> O primeiro numero é maior que o segundo?True/False*/
const condicao3 = numero1 > numero2 
console.log(`3-> O ${numero1} é maior que ${numero2}? ${condicao3}`)
    
/* 4-> O primeiro numero é menor que o segundo?True/False*/
const condicao4 = numero1 < numero2 
console.log(`4-> O ${numero1} é maior que ${numero2}? ${condicao4}`)

